// <auto-generated />
using System;
using IptasPeyzajApi.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IptasPeyzajApi.Migrations
{
    [DbContext(typeof(IptasPeyzajDbContext))]
    [Migration("20260813230433_InitialAzureSql")]
    partial class InitialAzureSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.BakimDetayEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BakimId")
                        .HasColumnType("int");

                    b.Property<string>("DriveDosyaId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirestoreId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("LegacyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ResimTip")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ResimUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("BakimId");

                    b.HasIndex("FirestoreId")
                        .IsUnique()
                        .HasFilter("[FirestoreId] IS NOT NULL");

                    b.HasIndex("LegacyKey")
                        .IsUnique();

                    b.ToTable("BakimDetaylari", (string)null);
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.BakimPersonelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BakimId")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.HasIndex("BakimId", "PersonelId")
                        .IsUnique();

                    b.ToTable("BakimPersonelleri", (string)null);
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.BakimPlaniEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("BakimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DurumKodu")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FirestoreId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IslemNotu")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriNo")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("BakimTarihi");

                    b.HasIndex("FirestoreId")
                        .IsUnique()
                        .HasFilter("[FirestoreId] IS NOT NULL");

                    b.HasIndex("MusteriId", "DurumKodu");

                    b.ToTable("BakimPlanlari", (string)null);
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.IsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EklentiNo")
                        .HasColumnType("int");

                    b.Property<string>("FirestoreId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("EklentiNo");

                    b.HasIndex("FirestoreId")
                        .IsUnique()
                        .HasFilter("[FirestoreId] IS NOT NULL");

                    b.ToTable("Isler", (string)null);
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.KullaniciEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("CepTelefonNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirestoreId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Tc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AktifMi");

                    b.HasIndex("FirestoreId")
                        .IsUnique()
                        .HasFilter("[FirestoreId] IS NOT NULL");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.MusteriEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("BelirliGunler")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("CaddeSokak")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Daire")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DurumKodu")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FirestoreId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("GorusmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mahalle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MekanTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MusteriNo")
                        .HasColumnType("int");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PeriyodikBakim")
                        .HasColumnType("int");

                    b.Property<string>("PeriyodikBakimTuru")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("SozlesmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DurumKodu");

                    b.HasIndex("FirestoreId")
                        .IsUnique()
                        .HasFilter("[FirestoreId] IS NOT NULL");

                    b.HasIndex("KayitTarihi");

                    b.HasIndex("MusteriNo")
                        .IsUnique();

                    b.ToTable("Musteriler", (string)null);
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.MusteriKullaniciEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirestoreId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FirestoreId")
                        .IsUnique()
                        .HasFilter("[FirestoreId] IS NOT NULL");

                    b.HasIndex("MusteriId");

                    b.HasIndex("KullaniciId", "MusteriId")
                        .IsUnique();

                    b.ToTable("MusteriKullanicilari", (string)null);
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.PersonelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DurumKodu")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("EskiPersonelId")
                        .HasColumnType("int");

                    b.Property<string>("FirestoreId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Gorev")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonelNo")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DurumKodu");

                    b.HasIndex("EskiPersonelId");

                    b.HasIndex("FirestoreId")
                        .IsUnique()
                        .HasFilter("[FirestoreId] IS NOT NULL");

                    b.HasIndex("PersonelNo");

                    b.ToTable("Personeller", (string)null);
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.TeklifEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DurumKodu")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FirestoreId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IslemNotu")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("TeklifTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DurumKodu");

                    b.HasIndex("FirestoreId")
                        .IsUnique()
                        .HasFilter("[FirestoreId] IS NOT NULL");

                    b.HasIndex("MusteriId");

                    b.HasIndex("MusteriNo");

                    b.ToTable("Teklifler", (string)null);
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.YapilacakIsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EklentiNo")
                        .HasColumnType("int");

                    b.Property<string>("FirestoreId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriNo")
                        .HasColumnType("int");

                    b.Property<string>("Not")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("FirestoreId")
                        .IsUnique()
                        .HasFilter("[FirestoreId] IS NOT NULL");

                    b.HasIndex("MusteriId");

                    b.ToTable("YapilacakIsler", (string)null);
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.YapilmayacakIsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EklentiNo")
                        .HasColumnType("int");

                    b.Property<string>("FirestoreId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriNo")
                        .HasColumnType("int");

                    b.Property<string>("Not")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("FirestoreId")
                        .IsUnique()
                        .HasFilter("[FirestoreId] IS NOT NULL");

                    b.HasIndex("MusteriId");

                    b.ToTable("YapilmayacakIsler", (string)null);
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.BakimDetayEntity", b =>
                {
                    b.HasOne("IptasPeyzajApi.Backend.Data.Entities.BakimPlaniEntity", "Bakim")
                        .WithMany("Detaylar")
                        .HasForeignKey("BakimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bakim");
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.BakimPersonelEntity", b =>
                {
                    b.HasOne("IptasPeyzajApi.Backend.Data.Entities.BakimPlaniEntity", "Bakim")
                        .WithMany("Personeller")
                        .HasForeignKey("BakimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IptasPeyzajApi.Backend.Data.Entities.PersonelEntity", "Personel")
                        .WithMany("Bakimlar")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bakim");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.BakimPlaniEntity", b =>
                {
                    b.HasOne("IptasPeyzajApi.Backend.Data.Entities.MusteriEntity", "Musteri")
                        .WithMany("BakimPlanlari")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.MusteriKullaniciEntity", b =>
                {
                    b.HasOne("IptasPeyzajApi.Backend.Data.Entities.KullaniciEntity", "Kullanici")
                        .WithMany("MusteriBaglantilari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IptasPeyzajApi.Backend.Data.Entities.MusteriEntity", "Musteri")
                        .WithMany("KullaniciBaglantilari")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.TeklifEntity", b =>
                {
                    b.HasOne("IptasPeyzajApi.Backend.Data.Entities.MusteriEntity", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.YapilacakIsEntity", b =>
                {
                    b.HasOne("IptasPeyzajApi.Backend.Data.Entities.MusteriEntity", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.YapilmayacakIsEntity", b =>
                {
                    b.HasOne("IptasPeyzajApi.Backend.Data.Entities.MusteriEntity", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.BakimPlaniEntity", b =>
                {
                    b.Navigation("Detaylar");

                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.KullaniciEntity", b =>
                {
                    b.Navigation("MusteriBaglantilari");
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.MusteriEntity", b =>
                {
                    b.Navigation("BakimPlanlari");

                    b.Navigation("KullaniciBaglantilari");
                });

            modelBuilder.Entity("IptasPeyzajApi.Backend.Data.Entities.PersonelEntity", b =>
                {
                    b.Navigation("Bakimlar");
                });
#pragma warning restore 612, 618
        }
    }
}
